# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developmentpractice',
            fields=[
                ('prac_id', models.AutoField(primary_key=True, serialize=False)),
                ('prac_name', models.CharField(blank=True, max_length=500, null=True)),
                ('prac_desc', models.TextField(blank=True, null=True)),
                ('prac_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'developmentpractice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Methodologies',
            fields=[
                ('method_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('method_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'methodologies',
                'managed': False,
            },
        ),
    ]
