# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradeworks',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_type', models.CharField(blank=True, max_length=100, null=True)),
                ('work_year', models.CharField(blank=True, max_length=4, null=True)),
                ('work_iswapp', models.NullBooleanField()),
                ('work_ismapp', models.NullBooleanField()),
                ('work_isdesk', models.NullBooleanField()),
                ('work_isaudi', models.NullBooleanField()),
                ('work_isweng', models.NullBooleanField()),
                ('work_isdbmn', models.NullBooleanField()),
                ('work_isothe', models.NullBooleanField()),
                ('work_uevalu', models.NullBooleanField()),
                ('work_status', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'gradeworks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Webaplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_types', models.CharField(blank=True, max_length=50, null=True)),
                ('app_cmenb', models.SmallIntegerField(blank=True, null=True)),
                ('app_lease', models.IntegerField(blank=True, null=True)),
                ('app_ueval', models.NullBooleanField()),
                ('app_lback', models.CharField(blank=True, max_length=500, null=True)),
                ('app_lfron', models.CharField(blank=True, max_length=500, null=True)),
                ('app_nsgdb', models.CharField(blank=True, max_length=100, null=True)),
                ('app_produ', models.NullBooleanField()),
                ('app_trodu', models.CharField(blank=True, max_length=50, null=True)),
                ('app_updat', models.NullBooleanField()),
                ('app_lupda', models.DateField(blank=True, null=True)),
                ('app_tcost', models.CharField(blank=True, max_length=50, null=True)),
                ('app_qualf', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'webaplications',
                'managed': False,
            },
        ),
    ]
