# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heuristicevaluation',
            fields=[
                ('ue_id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_sysvisi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_usrlang', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_ctrfree', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_constan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_feedbak', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_errprev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_flexefi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_edminim', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ue_helpdoc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'heuristicevaluation',
                'managed': False,
            },
        ),
    ]
